#remote_theme: saugatach/reverie
title: Welcome to webpage of Saugata Chatterjee!
description: Data analysis, machine learning, and physics meet here
# baseurl: '/reverie/'

theme: jekyll-theme-minimal