title:              Bytes of wisdom
email:              saugata.ch@gmail.com
description:        We share tutorials, ideas, and recipes on this blog on physics, linux, and data analysis
author:             Saugata Chatterjee
baseurl:            ""
#url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   saugatach
github_username:    saugatach
#facebook_username:  StartBootstrap
#instagram_username:
linkedin_username:  saugatach

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
